### get tyeams
GET  https://vfapi-production.up.railway.app/api/players HTTP/1.1

### get teams
GET https://vfapi-production.up.railway.app/api/matches HTTP/1.1

### get teams
GET https://vfapi-production.up.railway.app:8080/api/matchevents/match/2 HTTP/1.1
